spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  application:
    name: solution_9_11
  datasource:
    generate-unique-name: false
    name: testdb
  h2:
    console:
      enabled: true
  # http://localhost:28080/h2-console/
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

server:
  port: 28080